[tox]
envlist =
       py312-lint,
       py312-types,
       {py312,py313}-django{4.2,5.2}-drf{3.15},
       {py314}-django{6.0}-drf{3.16},
skip_missing_interpreters = true

[testenv]
commands = pytest
setenv =
       PYTHONDONTWRITEBYTECODE=1
passenv =
       CI
deps =
       django4.2: Django>=4.2,<5.0
       django5.0: Django>=5.0,<5.1
       django5.1: Django>=5.1,<5.2
       django5.2: Django>=5.2b1,<5.3
       django6.0: Django>=6.0,<7.0

       drf3.14: djangorestframework>=3.14,<3.15
       drf3.15: djangorestframework>=3.15,<3.16
       drf3.16: djangorestframework>=3.15,<3.16

       pytest
       pytest-django
       pytest-cov
       drf-spectacular

[testenv:py312-types]
commands =
       mypy .
deps =
       mypy
       pytest
       django-stubs
       djangorestframework-stubs
       drf-spectacular

[testenv:py312-lint]
commands =
       ruff check .
       ruff format --check .
deps =
       ruff
